### ISSUE TITLE
Modify the path to rpmdb

### ISSUE THREAD

**Issue by morpheuslord** [packit/rpm-shim#8]
### Description

Hello there,

I am working on an SBOM utility that is capable of static and chroot-based analysis of red-hat-based images and your tool can be a goldmine to integrate but the issue is the image I will be scanning is a mounted volume and I am not able to understand how your tool accesses the DB cause if I can't edit the path to the db I wont be to access the images properly.

### Benefit

The main benefits I can see are better integration and extended support.

### Importance

This is quite important for me and for devs looking forward to integrating your tool.

### Workaround

- [ ] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by nforro** [comment]
Hi, rpm-shim doesn't access anything, it only allows you to import and use **RPM Python bindings** inside a virtualenv. I think you need to direct your question there: https://github.com/rpm-software-management/rpm

**Comment by morpheuslord** [comment]
Thanks I will look into it 👍

**Comment by nforro** [comment]
@morpheuslord Just a hint, this may be what you are after (it may be outdated though): https://jfearn.fedorapeople.org/en-US/RPM/4/html/RPM_Guide/ch16s03.html

**Comment by morpheuslord** [comment]
> @morpheuslord Just a hint, this may be what you are after (it may be outdated though): https://jfearn.fedorapeople.org/en-US/RPM/4/html/RPM_Guide/ch16s03.html

That is exactly what I needed thanks a lot.
